dataset_path: /home/user/datasets/echkina/
data_path: AllPumps_Data.csv
new_data_path: new_AllPumps_Data.csv

info_train_path: Pumps_Struct_All_Trains.csv
new_info_train_path: new_Pumps_Struct_All_Trains.csv
info_points_path: Pumps_Struct_All_Points.csv
new_info_points_path: new_Pumps_Struct_All_Points.csv
info_measures_path: Pumps_Struct_All_Measures.csv
new_info_measures_path: new_Pumps_Struct_All_Measures.csv
