---

# Общие настройки
main:
  # Директория для сохранения чекпоинтов моделей
  checkpoint_save_dir: "./checkpoints_fully_10_sgd/"
  # Название чекпоинтов
  checkpoint_string: "model_a{0}_p{1}_u{2}_d{3}_epoch{4}.pth"
  # Максимальное количество чекпоинтов
  max_count_checkpoint: 10

  # Директория для сохранения валидных объектов
  valid_objects_save_dir: "./pickle_dumps_valid_train/"
  # Название файла с валидными объектами
  valid_objects_string: "dump_random{0}_a{1}_p{2}_u{3}_d{4}.pl"
  # Отключить загрузку файлов валидных объектов для определенной пары (unit, direction)
  off_load_pickle_for_unit_direction: []

  # первый unit
  unit_start: 0
  # последний unit
  unit_last: 2
  # первый direction
  direction_start: 1
  # последний direction
  direction_last: 3
  # отключить обработку определенной пары (unit, direction)
  off_unit_direction: []
  # Путь для модели загрузки
  checkpoint_save: {}

dataloader:
  # valid_size определяется автоматически
  test_size: 0.1
  train_size: 0.7
  random_state: 25

# Настройки модели
model:
  # Тип модели
  tp: fully_model # [lstm_model, fully_model]
  # Оптимизатор
  optimizer: SGD # [Adam, SGD] get from optim. ....
  # Функция потерь
  loss_function: MSELoss # [L1Loss, MSELoss, CrossEntropyLoss] get from nn. ...
  # Максимальное количество эпох
  epoch: 1000
  # Начальный шаг обучения
  lr: 0.00001
  # Измненине шага обучения (умножение на заданное число)
  lr_decay: 0.5
  # Шаг изменения
  lr_step: 300

# Настройки
settings:
  # Отключение второстепенных выводов
  off_all_prints: False
  # Отключение вывода времени
  print_time: False
  # Отключение вывода рандомного вывода предсказания
  print_predict: False
  # Вывод рандомного предсказания каждые...:
  print_predict_step: 5000

# Настройка wandb
wandb:
  turn_on: True
  # Название проекта
  project: "echkina"
  # Имя запуска
  name: "echkina_{0}_{1}_{2}_model_unit_{3}_direction_{4}"

# Настройка полносвязной модели
fully_model:
  num_of_layers: 10

# Настройка модели временного ряда
lstm_model:
  hidden_size: 2000
