---
# Общие настройки
main:
  # Директория для сохранения чекпоинтов моделей
  checkpoint_save_dir:
  # Название чекпоинтов
  checkpoint_string:
  # Максимальное количество чекпоинтов
  max_count_checkpoint:

  # Директория для сохранения валидных объектов
  valid_objects_save_dir:
  # Название файла с валидными объектами
  valid_objects_string:
  # Отключить загрузку файлов валидных объектов для определенной пары (unit, direction)
  off_load_pickle_for_unit_direction: []

  # первый unit
  unit_start: 0
  # последний unit
  unit_last: 2
  # первый direction
  direction_start: 1
  # последний direction
  direction_last: 3
  # отключить обработку определенной пары (unit, direction)
  off_unit_direction: []

  # Путь для модели загрузки
  checkpoint_save:
    (0, 1): "./checkpoints_fully_10_adam/model_a5_p3_u0_d1_epoch581.pth"
    (0, 2): "./checkpoints_lstm_2000_adam/model_a5_p3_u0_d2_epoch999.pth"
    (0, 3): "./checkpoints_lstm_2000_adam/model_a5_p3_u0_d3_epoch440.pth"
    (1, 1): "./checkpoints_lstm_2000_adam/model_a5_p3_u1_d1_epoch999.pth"
    (1, 2): "./checkpoints_lstm_2000_adam/model_a5_p3_u1_d2_epoch251.pth"
    (1, 3): "./checkpoints_lstm_500_adam/model_a5_p3_u1_d3_epoch999.pth"
    (2, 1): "./checkpoints_lstm_500_adam/model_a5_p3_u2_d1_epoch999.pth"
    (2, 2): "./checkpoints_lstm_500_adam/model_a5_p3_u2_d2_epoch999.pth"
    (2, 3): "./checkpoints_lstm_500_adam/model_a5_p3_u2_d3_epoch999.pth"

dataloader:
  # valid_size определяется автоматически
  test_size:
  train_size:
  random_state: 25

# Настройки модели
model:
  # Тип модели
  tp:
  # Оптимизатор
  optimizer:
  # Функция потерь
  loss_function:
  # Максимальное количество эпох
  epoch:
  # Начальный шаг обучения
  lr:
  # Измненине шага обучения (умножение на заданное число)
  lr_decay:
  # Шаг изменения
  lr_step:

# Настройки
settings:
  # Отключение второстепенных выводов
  off_all_prints: False
  # Отключение вывода времени
  print_time: False
  # Отключение вывода рандомного вывода предсказания
  print_predict: False
  # Вывод рандомного предсказания каждые...:
  print_predict_step: 5000

# Настройка wandb
wandb:
  turn_on: False
  # Название проекта
  project:
  # Имя запуска
  name:

# Настройка полносвязной модели
fully_model:
  num_of_layers: 5

# Настройка модели временного ряда
lstm_model:
  hidden_size: 500
